#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DashboardAutoDEV")]
	public partial class DashboardAutoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertCustomerPhone(CustomerPhone instance);
    partial void UpdateCustomerPhone(CustomerPhone instance);
    partial void DeleteCustomerPhone(CustomerPhone instance);
    partial void InsertCustomerEmail(CustomerEmail instance);
    partial void UpdateCustomerEmail(CustomerEmail instance);
    partial void DeleteCustomerEmail(CustomerEmail instance);
    #endregion
		
		public DashboardAutoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DashboardAutoDEVConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DashboardAutoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DashboardAutoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DashboardAutoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DashboardAutoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<CustomerPhone> CustomerPhones
		{
			get
			{
				return this.GetTable<CustomerPhone>();
			}
		}
		
		public System.Data.Linq.Table<CustomerEmail> CustomerEmails
		{
			get
			{
				return this.GetTable<CustomerEmail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerPK;
		
		private string _LKNamePrefixFK;
		
		private string _LKNameSuffixFK;
		
		private string _Name;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _MiddleName;
		
		private System.Nullable<char> _Sex;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private bool _ActiveInd;
		
		private int _CustomerAccountFK;
		
		private int _LKCustomerTypeFK;
		
		private int _LKRelationshipTypeFK;
		
		private System.Nullable<bool> _HouseholdMemberInd;
		
		private System.Nullable<bool> _ExcludedDriverInd;
		
		private System.Nullable<bool> _VehicleAdditionalInsuredInd;
		
		private bool _CustomerRepInd;
		
		private string _GoesByName;
		
		private string _DriversLicenseNo;
		
		private string _DriversLicenseStateFK;
		
		private System.Nullable<char> _MaritalStatus;
		
		private int _LKOccupationFK;
		
		private int _LKCommPrefFK;
		
		private System.Nullable<int> _CreditScore;
		
		private System.Nullable<bool> _UndisclosedDriverInd;
		
		private System.Nullable<bool> _CollectorClubInd;
		
		private string _CollectorClubNotes;
		
		private System.DateTime _LastUpdTimestamp;
		
		private string _LastUpdUser;
		
		private System.Nullable<bool> _PolicyExcludedDriverInd;
		
		private System.Nullable<bool> _PolicyAdditionalInsuredInd;
		
		private string _EntityCustomerName;
		
		private System.Nullable<bool> _ElectronicRenewalPreferenceInd;
		
		private System.Nullable<int> _PreferredContactFK;
		
		private System.Nullable<System.DateTime> _CreditScoreReportDate;
		
		private System.Nullable<bool> _OperatesCollectorVehiclesInd;
		
		private System.Nullable<bool> _MarketingMaterialInd;
		
		private string _WebSiteURL;
		
		private System.Data.Linq.Binary _HIARowVersion;
		
		private string _alias;
		
		private System.Nullable<short> _tmpCustNum;
		
		private System.Nullable<int> _tmpLegacyKey;
		
		private string _tmpPolicyNumber;
		
		private System.Nullable<short> _tmpVehicleNumber;
		
		private System.Nullable<int> _YearsLicensed;
		
		private System.Nullable<int> _YearsInCollectorCarHobby;
		
		private System.Nullable<bool> _OptOutMailingsInd;
		
		private System.Nullable<bool> _EstimatedDateOfBirthInd;
		
		private System.Nullable<System.DateTime> _ElectronicRenewalConfirmationDate;
		
		private System.Nullable<System.DateTime> _ElectronicRenewalSignupDate;
		
		private System.Nullable<bool> _ReportedSeniorCitizenInd;
		
		private System.Nullable<int> _ReportedYearsLicensed;
		
		private System.Nullable<bool> _SecondaryIsAnOrInd;
		
		private System.Nullable<bool> _ForeignAddressInd;
		
		private System.Nullable<int> _HobbyStartYear;
		
		private System.Nullable<System.DateTime> _YearsLicensedReevaluatedForPolicyEffectiveDate;
		
		private System.Nullable<int> _PendingReportedYearsLicensed;
		
		private System.Nullable<bool> _CommercialInd;
		
		private System.Nullable<bool> _SecondaryIsNamedInsuredInd;
		
		private string _Occupation;
		
		private System.Nullable<bool> _NotLicensedInd;
		
		private System.Nullable<System.DateTime> _ActiveDate;
		
		private System.Nullable<System.DateTime> _FlexTierTriggerDate;
		
		private System.Nullable<int> _CustomerAccountSTPUWRptResponseDriverFK;
		
		private System.Nullable<int> _MonthFirstLicensed;
		
		private System.Nullable<int> _YearFirstLicensed;
		
		private System.Nullable<int> _PersonFK;
		
		private System.Data.Linq.Binary _DriversLicenseNoEncrypted;
		
		private System.Nullable<bool> _DIFMFlexGrandfatherInd;
		
		private System.Nullable<bool> _LicensedLessThanThreeYearsInd;
		
		private System.Nullable<bool> _UnknownDLNoInd;
		
		private System.Nullable<System.DateTime> _RelevantDate;
		
		private System.Nullable<int> _LKABGridStepScoreFK;
		
		private EntitySet<Customer> _Customers;
		
		private EntitySet<CustomerPhone> _CustomerPhones;
		
		private EntitySet<CustomerEmail> _CustomerEmails;
		
		private EntityRef<Customer> _Customer1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerPKChanging(int value);
    partial void OnCustomerPKChanged();
    partial void OnLKNamePrefixFKChanging(string value);
    partial void OnLKNamePrefixFKChanged();
    partial void OnLKNameSuffixFKChanging(string value);
    partial void OnLKNameSuffixFKChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnSexChanging(System.Nullable<char> value);
    partial void OnSexChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnActiveIndChanging(bool value);
    partial void OnActiveIndChanged();
    partial void OnCustomerAccountFKChanging(int value);
    partial void OnCustomerAccountFKChanged();
    partial void OnLKCustomerTypeFKChanging(int value);
    partial void OnLKCustomerTypeFKChanged();
    partial void OnLKRelationshipTypeFKChanging(int value);
    partial void OnLKRelationshipTypeFKChanged();
    partial void OnHouseholdMemberIndChanging(System.Nullable<bool> value);
    partial void OnHouseholdMemberIndChanged();
    partial void OnExcludedDriverIndChanging(System.Nullable<bool> value);
    partial void OnExcludedDriverIndChanged();
    partial void OnVehicleAdditionalInsuredIndChanging(System.Nullable<bool> value);
    partial void OnVehicleAdditionalInsuredIndChanged();
    partial void OnCustomerRepIndChanging(bool value);
    partial void OnCustomerRepIndChanged();
    partial void OnGoesByNameChanging(string value);
    partial void OnGoesByNameChanged();
    partial void OnDriversLicenseNoChanging(string value);
    partial void OnDriversLicenseNoChanged();
    partial void OnDriversLicenseStateFKChanging(string value);
    partial void OnDriversLicenseStateFKChanged();
    partial void OnMaritalStatusChanging(System.Nullable<char> value);
    partial void OnMaritalStatusChanged();
    partial void OnLKOccupationFKChanging(int value);
    partial void OnLKOccupationFKChanged();
    partial void OnLKCommPrefFKChanging(int value);
    partial void OnLKCommPrefFKChanged();
    partial void OnCreditScoreChanging(System.Nullable<int> value);
    partial void OnCreditScoreChanged();
    partial void OnUndisclosedDriverIndChanging(System.Nullable<bool> value);
    partial void OnUndisclosedDriverIndChanged();
    partial void OnCollectorClubIndChanging(System.Nullable<bool> value);
    partial void OnCollectorClubIndChanged();
    partial void OnCollectorClubNotesChanging(string value);
    partial void OnCollectorClubNotesChanged();
    partial void OnLastUpdTimestampChanging(System.DateTime value);
    partial void OnLastUpdTimestampChanged();
    partial void OnLastUpdUserChanging(string value);
    partial void OnLastUpdUserChanged();
    partial void OnPolicyExcludedDriverIndChanging(System.Nullable<bool> value);
    partial void OnPolicyExcludedDriverIndChanged();
    partial void OnPolicyAdditionalInsuredIndChanging(System.Nullable<bool> value);
    partial void OnPolicyAdditionalInsuredIndChanged();
    partial void OnEntityCustomerNameChanging(string value);
    partial void OnEntityCustomerNameChanged();
    partial void OnElectronicRenewalPreferenceIndChanging(System.Nullable<bool> value);
    partial void OnElectronicRenewalPreferenceIndChanged();
    partial void OnPreferredContactFKChanging(System.Nullable<int> value);
    partial void OnPreferredContactFKChanged();
    partial void OnCreditScoreReportDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreditScoreReportDateChanged();
    partial void OnOperatesCollectorVehiclesIndChanging(System.Nullable<bool> value);
    partial void OnOperatesCollectorVehiclesIndChanged();
    partial void OnMarketingMaterialIndChanging(System.Nullable<bool> value);
    partial void OnMarketingMaterialIndChanged();
    partial void OnWebSiteURLChanging(string value);
    partial void OnWebSiteURLChanged();
    partial void OnHIARowVersionChanging(System.Data.Linq.Binary value);
    partial void OnHIARowVersionChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OntmpCustNumChanging(System.Nullable<short> value);
    partial void OntmpCustNumChanged();
    partial void OntmpLegacyKeyChanging(System.Nullable<int> value);
    partial void OntmpLegacyKeyChanged();
    partial void OntmpPolicyNumberChanging(string value);
    partial void OntmpPolicyNumberChanged();
    partial void OntmpVehicleNumberChanging(System.Nullable<short> value);
    partial void OntmpVehicleNumberChanged();
    partial void OnYearsLicensedChanging(System.Nullable<int> value);
    partial void OnYearsLicensedChanged();
    partial void OnYearsInCollectorCarHobbyChanging(System.Nullable<int> value);
    partial void OnYearsInCollectorCarHobbyChanged();
    partial void OnOptOutMailingsIndChanging(System.Nullable<bool> value);
    partial void OnOptOutMailingsIndChanged();
    partial void OnEstimatedDateOfBirthIndChanging(System.Nullable<bool> value);
    partial void OnEstimatedDateOfBirthIndChanged();
    partial void OnElectronicRenewalConfirmationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnElectronicRenewalConfirmationDateChanged();
    partial void OnElectronicRenewalSignupDateChanging(System.Nullable<System.DateTime> value);
    partial void OnElectronicRenewalSignupDateChanged();
    partial void OnReportedSeniorCitizenIndChanging(System.Nullable<bool> value);
    partial void OnReportedSeniorCitizenIndChanged();
    partial void OnReportedYearsLicensedChanging(System.Nullable<int> value);
    partial void OnReportedYearsLicensedChanged();
    partial void OnSecondaryIsAnOrIndChanging(System.Nullable<bool> value);
    partial void OnSecondaryIsAnOrIndChanged();
    partial void OnForeignAddressIndChanging(System.Nullable<bool> value);
    partial void OnForeignAddressIndChanged();
    partial void OnHobbyStartYearChanging(System.Nullable<int> value);
    partial void OnHobbyStartYearChanged();
    partial void OnYearsLicensedReevaluatedForPolicyEffectiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnYearsLicensedReevaluatedForPolicyEffectiveDateChanged();
    partial void OnPendingReportedYearsLicensedChanging(System.Nullable<int> value);
    partial void OnPendingReportedYearsLicensedChanged();
    partial void OnCommercialIndChanging(System.Nullable<bool> value);
    partial void OnCommercialIndChanged();
    partial void OnSecondaryIsNamedInsuredIndChanging(System.Nullable<bool> value);
    partial void OnSecondaryIsNamedInsuredIndChanged();
    partial void OnOccupationChanging(string value);
    partial void OnOccupationChanged();
    partial void OnNotLicensedIndChanging(System.Nullable<bool> value);
    partial void OnNotLicensedIndChanged();
    partial void OnActiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnActiveDateChanged();
    partial void OnFlexTierTriggerDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFlexTierTriggerDateChanged();
    partial void OnCustomerAccountSTPUWRptResponseDriverFKChanging(System.Nullable<int> value);
    partial void OnCustomerAccountSTPUWRptResponseDriverFKChanged();
    partial void OnMonthFirstLicensedChanging(System.Nullable<int> value);
    partial void OnMonthFirstLicensedChanged();
    partial void OnYearFirstLicensedChanging(System.Nullable<int> value);
    partial void OnYearFirstLicensedChanged();
    partial void OnPersonFKChanging(System.Nullable<int> value);
    partial void OnPersonFKChanged();
    partial void OnDriversLicenseNoEncryptedChanging(System.Data.Linq.Binary value);
    partial void OnDriversLicenseNoEncryptedChanged();
    partial void OnDIFMFlexGrandfatherIndChanging(System.Nullable<bool> value);
    partial void OnDIFMFlexGrandfatherIndChanged();
    partial void OnLicensedLessThanThreeYearsIndChanging(System.Nullable<bool> value);
    partial void OnLicensedLessThanThreeYearsIndChanged();
    partial void OnUnknownDLNoIndChanging(System.Nullable<bool> value);
    partial void OnUnknownDLNoIndChanged();
    partial void OnRelevantDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRelevantDateChanged();
    partial void OnLKABGridStepScoreFKChanging(System.Nullable<int> value);
    partial void OnLKABGridStepScoreFKChanged();
    #endregion
		
		public Customer()
		{
			this._Customers = new EntitySet<Customer>(new Action<Customer>(this.attach_Customers), new Action<Customer>(this.detach_Customers));
			this._CustomerPhones = new EntitySet<CustomerPhone>(new Action<CustomerPhone>(this.attach_CustomerPhones), new Action<CustomerPhone>(this.detach_CustomerPhones));
			this._CustomerEmails = new EntitySet<CustomerEmail>(new Action<CustomerEmail>(this.attach_CustomerEmails), new Action<CustomerEmail>(this.detach_CustomerEmails));
			this._Customer1 = default(EntityRef<Customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerPK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CustomerPK
		{
			get
			{
				return this._CustomerPK;
			}
			set
			{
				if ((this._CustomerPK != value))
				{
					this.OnCustomerPKChanging(value);
					this.SendPropertyChanging();
					this._CustomerPK = value;
					this.SendPropertyChanged("CustomerPK");
					this.OnCustomerPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKNamePrefixFK", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string LKNamePrefixFK
		{
			get
			{
				return this._LKNamePrefixFK;
			}
			set
			{
				if ((this._LKNamePrefixFK != value))
				{
					this.OnLKNamePrefixFKChanging(value);
					this.SendPropertyChanging();
					this._LKNamePrefixFK = value;
					this.SendPropertyChanged("LKNamePrefixFK");
					this.OnLKNamePrefixFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKNameSuffixFK", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string LKNameSuffixFK
		{
			get
			{
				return this._LKNameSuffixFK;
			}
			set
			{
				if ((this._LKNameSuffixFK != value))
				{
					this.OnLKNameSuffixFKChanging(value);
					this.SendPropertyChanging();
					this._LKNameSuffixFK = value;
					this.SendPropertyChanged("LKNameSuffixFK");
					this.OnLKNameSuffixFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="Char(60)", UpdateCheck=UpdateCheck.Never)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(40)", UpdateCheck=UpdateCheck.Never)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveInd", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool ActiveInd
		{
			get
			{
				return this._ActiveInd;
			}
			set
			{
				if ((this._ActiveInd != value))
				{
					this.OnActiveIndChanging(value);
					this.SendPropertyChanging();
					this._ActiveInd = value;
					this.SendPropertyChanged("ActiveInd");
					this.OnActiveIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerAccountFK", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CustomerAccountFK
		{
			get
			{
				return this._CustomerAccountFK;
			}
			set
			{
				if ((this._CustomerAccountFK != value))
				{
					this.OnCustomerAccountFKChanging(value);
					this.SendPropertyChanging();
					this._CustomerAccountFK = value;
					this.SendPropertyChanged("CustomerAccountFK");
					this.OnCustomerAccountFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKCustomerTypeFK", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int LKCustomerTypeFK
		{
			get
			{
				return this._LKCustomerTypeFK;
			}
			set
			{
				if ((this._LKCustomerTypeFK != value))
				{
					this.OnLKCustomerTypeFKChanging(value);
					this.SendPropertyChanging();
					this._LKCustomerTypeFK = value;
					this.SendPropertyChanged("LKCustomerTypeFK");
					this.OnLKCustomerTypeFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKRelationshipTypeFK", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int LKRelationshipTypeFK
		{
			get
			{
				return this._LKRelationshipTypeFK;
			}
			set
			{
				if ((this._LKRelationshipTypeFK != value))
				{
					this.OnLKRelationshipTypeFKChanging(value);
					this.SendPropertyChanging();
					this._LKRelationshipTypeFK = value;
					this.SendPropertyChanged("LKRelationshipTypeFK");
					this.OnLKRelationshipTypeFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseholdMemberInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> HouseholdMemberInd
		{
			get
			{
				return this._HouseholdMemberInd;
			}
			set
			{
				if ((this._HouseholdMemberInd != value))
				{
					this.OnHouseholdMemberIndChanging(value);
					this.SendPropertyChanging();
					this._HouseholdMemberInd = value;
					this.SendPropertyChanged("HouseholdMemberInd");
					this.OnHouseholdMemberIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExcludedDriverInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> ExcludedDriverInd
		{
			get
			{
				return this._ExcludedDriverInd;
			}
			set
			{
				if ((this._ExcludedDriverInd != value))
				{
					this.OnExcludedDriverIndChanging(value);
					this.SendPropertyChanging();
					this._ExcludedDriverInd = value;
					this.SendPropertyChanged("ExcludedDriverInd");
					this.OnExcludedDriverIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleAdditionalInsuredInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> VehicleAdditionalInsuredInd
		{
			get
			{
				return this._VehicleAdditionalInsuredInd;
			}
			set
			{
				if ((this._VehicleAdditionalInsuredInd != value))
				{
					this.OnVehicleAdditionalInsuredIndChanging(value);
					this.SendPropertyChanging();
					this._VehicleAdditionalInsuredInd = value;
					this.SendPropertyChanged("VehicleAdditionalInsuredInd");
					this.OnVehicleAdditionalInsuredIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerRepInd", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool CustomerRepInd
		{
			get
			{
				return this._CustomerRepInd;
			}
			set
			{
				if ((this._CustomerRepInd != value))
				{
					this.OnCustomerRepIndChanging(value);
					this.SendPropertyChanging();
					this._CustomerRepInd = value;
					this.SendPropertyChanged("CustomerRepInd");
					this.OnCustomerRepIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoesByName", DbType="VarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string GoesByName
		{
			get
			{
				return this._GoesByName;
			}
			set
			{
				if ((this._GoesByName != value))
				{
					this.OnGoesByNameChanging(value);
					this.SendPropertyChanging();
					this._GoesByName = value;
					this.SendPropertyChanged("GoesByName");
					this.OnGoesByNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriversLicenseNo", DbType="Char(25) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DriversLicenseNo
		{
			get
			{
				return this._DriversLicenseNo;
			}
			set
			{
				if ((this._DriversLicenseNo != value))
				{
					this.OnDriversLicenseNoChanging(value);
					this.SendPropertyChanging();
					this._DriversLicenseNo = value;
					this.SendPropertyChanged("DriversLicenseNo");
					this.OnDriversLicenseNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriversLicenseStateFK", DbType="Char(2) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DriversLicenseStateFK
		{
			get
			{
				return this._DriversLicenseStateFK;
			}
			set
			{
				if ((this._DriversLicenseStateFK != value))
				{
					this.OnDriversLicenseStateFKChanging(value);
					this.SendPropertyChanging();
					this._DriversLicenseStateFK = value;
					this.SendPropertyChanged("DriversLicenseStateFK");
					this.OnDriversLicenseStateFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this.OnMaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._MaritalStatus = value;
					this.SendPropertyChanged("MaritalStatus");
					this.OnMaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKOccupationFK", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int LKOccupationFK
		{
			get
			{
				return this._LKOccupationFK;
			}
			set
			{
				if ((this._LKOccupationFK != value))
				{
					this.OnLKOccupationFKChanging(value);
					this.SendPropertyChanging();
					this._LKOccupationFK = value;
					this.SendPropertyChanged("LKOccupationFK");
					this.OnLKOccupationFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKCommPrefFK", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int LKCommPrefFK
		{
			get
			{
				return this._LKCommPrefFK;
			}
			set
			{
				if ((this._LKCommPrefFK != value))
				{
					this.OnLKCommPrefFKChanging(value);
					this.SendPropertyChanging();
					this._LKCommPrefFK = value;
					this.SendPropertyChanged("LKCommPrefFK");
					this.OnLKCommPrefFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditScore", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CreditScore
		{
			get
			{
				return this._CreditScore;
			}
			set
			{
				if ((this._CreditScore != value))
				{
					this.OnCreditScoreChanging(value);
					this.SendPropertyChanging();
					this._CreditScore = value;
					this.SendPropertyChanged("CreditScore");
					this.OnCreditScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UndisclosedDriverInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> UndisclosedDriverInd
		{
			get
			{
				return this._UndisclosedDriverInd;
			}
			set
			{
				if ((this._UndisclosedDriverInd != value))
				{
					this.OnUndisclosedDriverIndChanging(value);
					this.SendPropertyChanging();
					this._UndisclosedDriverInd = value;
					this.SendPropertyChanged("UndisclosedDriverInd");
					this.OnUndisclosedDriverIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectorClubInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> CollectorClubInd
		{
			get
			{
				return this._CollectorClubInd;
			}
			set
			{
				if ((this._CollectorClubInd != value))
				{
					this.OnCollectorClubIndChanging(value);
					this.SendPropertyChanging();
					this._CollectorClubInd = value;
					this.SendPropertyChanged("CollectorClubInd");
					this.OnCollectorClubIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollectorClubNotes", DbType="VarChar(500) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CollectorClubNotes
		{
			get
			{
				return this._CollectorClubNotes;
			}
			set
			{
				if ((this._CollectorClubNotes != value))
				{
					this.OnCollectorClubNotesChanging(value);
					this.SendPropertyChanging();
					this._CollectorClubNotes = value;
					this.SendPropertyChanged("CollectorClubNotes");
					this.OnCollectorClubNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdTimestamp", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastUpdTimestamp
		{
			get
			{
				return this._LastUpdTimestamp;
			}
			set
			{
				if ((this._LastUpdTimestamp != value))
				{
					this.OnLastUpdTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdTimestamp = value;
					this.SendPropertyChanged("LastUpdTimestamp");
					this.OnLastUpdTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdUser", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string LastUpdUser
		{
			get
			{
				return this._LastUpdUser;
			}
			set
			{
				if ((this._LastUpdUser != value))
				{
					this.OnLastUpdUserChanging(value);
					this.SendPropertyChanging();
					this._LastUpdUser = value;
					this.SendPropertyChanged("LastUpdUser");
					this.OnLastUpdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyExcludedDriverInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> PolicyExcludedDriverInd
		{
			get
			{
				return this._PolicyExcludedDriverInd;
			}
			set
			{
				if ((this._PolicyExcludedDriverInd != value))
				{
					this.OnPolicyExcludedDriverIndChanging(value);
					this.SendPropertyChanging();
					this._PolicyExcludedDriverInd = value;
					this.SendPropertyChanged("PolicyExcludedDriverInd");
					this.OnPolicyExcludedDriverIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolicyAdditionalInsuredInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> PolicyAdditionalInsuredInd
		{
			get
			{
				return this._PolicyAdditionalInsuredInd;
			}
			set
			{
				if ((this._PolicyAdditionalInsuredInd != value))
				{
					this.OnPolicyAdditionalInsuredIndChanging(value);
					this.SendPropertyChanging();
					this._PolicyAdditionalInsuredInd = value;
					this.SendPropertyChanged("PolicyAdditionalInsuredInd");
					this.OnPolicyAdditionalInsuredIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityCustomerName", DbType="VarChar(75) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string EntityCustomerName
		{
			get
			{
				return this._EntityCustomerName;
			}
			set
			{
				if ((this._EntityCustomerName != value))
				{
					this.OnEntityCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._EntityCustomerName = value;
					this.SendPropertyChanged("EntityCustomerName");
					this.OnEntityCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElectronicRenewalPreferenceInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> ElectronicRenewalPreferenceInd
		{
			get
			{
				return this._ElectronicRenewalPreferenceInd;
			}
			set
			{
				if ((this._ElectronicRenewalPreferenceInd != value))
				{
					this.OnElectronicRenewalPreferenceIndChanging(value);
					this.SendPropertyChanging();
					this._ElectronicRenewalPreferenceInd = value;
					this.SendPropertyChanged("ElectronicRenewalPreferenceInd");
					this.OnElectronicRenewalPreferenceIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredContactFK", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PreferredContactFK
		{
			get
			{
				return this._PreferredContactFK;
			}
			set
			{
				if ((this._PreferredContactFK != value))
				{
					if (this._Customer1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPreferredContactFKChanging(value);
					this.SendPropertyChanging();
					this._PreferredContactFK = value;
					this.SendPropertyChanged("PreferredContactFK");
					this.OnPreferredContactFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditScoreReportDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CreditScoreReportDate
		{
			get
			{
				return this._CreditScoreReportDate;
			}
			set
			{
				if ((this._CreditScoreReportDate != value))
				{
					this.OnCreditScoreReportDateChanging(value);
					this.SendPropertyChanging();
					this._CreditScoreReportDate = value;
					this.SendPropertyChanged("CreditScoreReportDate");
					this.OnCreditScoreReportDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatesCollectorVehiclesInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> OperatesCollectorVehiclesInd
		{
			get
			{
				return this._OperatesCollectorVehiclesInd;
			}
			set
			{
				if ((this._OperatesCollectorVehiclesInd != value))
				{
					this.OnOperatesCollectorVehiclesIndChanging(value);
					this.SendPropertyChanging();
					this._OperatesCollectorVehiclesInd = value;
					this.SendPropertyChanged("OperatesCollectorVehiclesInd");
					this.OnOperatesCollectorVehiclesIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketingMaterialInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> MarketingMaterialInd
		{
			get
			{
				return this._MarketingMaterialInd;
			}
			set
			{
				if ((this._MarketingMaterialInd != value))
				{
					this.OnMarketingMaterialIndChanging(value);
					this.SendPropertyChanging();
					this._MarketingMaterialInd = value;
					this.SendPropertyChanged("MarketingMaterialInd");
					this.OnMarketingMaterialIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebSiteURL", DbType="VarChar(75) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string WebSiteURL
		{
			get
			{
				return this._WebSiteURL;
			}
			set
			{
				if ((this._WebSiteURL != value))
				{
					this.OnWebSiteURLChanging(value);
					this.SendPropertyChanging();
					this._WebSiteURL = value;
					this.SendPropertyChanged("WebSiteURL");
					this.OnWebSiteURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIARowVersion", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HIARowVersion
		{
			get
			{
				return this._HIARowVersion;
			}
			set
			{
				if ((this._HIARowVersion != value))
				{
					this.OnHIARowVersionChanging(value);
					this.SendPropertyChanging();
					this._HIARowVersion = value;
					this.SendPropertyChanged("HIARowVersion");
					this.OnHIARowVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="VarChar(75) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmpCustNum", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> tmpCustNum
		{
			get
			{
				return this._tmpCustNum;
			}
			set
			{
				if ((this._tmpCustNum != value))
				{
					this.OntmpCustNumChanging(value);
					this.SendPropertyChanging();
					this._tmpCustNum = value;
					this.SendPropertyChanged("tmpCustNum");
					this.OntmpCustNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmpLegacyKey", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> tmpLegacyKey
		{
			get
			{
				return this._tmpLegacyKey;
			}
			set
			{
				if ((this._tmpLegacyKey != value))
				{
					this.OntmpLegacyKeyChanging(value);
					this.SendPropertyChanging();
					this._tmpLegacyKey = value;
					this.SendPropertyChanged("tmpLegacyKey");
					this.OntmpLegacyKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmpPolicyNumber", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string tmpPolicyNumber
		{
			get
			{
				return this._tmpPolicyNumber;
			}
			set
			{
				if ((this._tmpPolicyNumber != value))
				{
					this.OntmpPolicyNumberChanging(value);
					this.SendPropertyChanging();
					this._tmpPolicyNumber = value;
					this.SendPropertyChanged("tmpPolicyNumber");
					this.OntmpPolicyNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmpVehicleNumber", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> tmpVehicleNumber
		{
			get
			{
				return this._tmpVehicleNumber;
			}
			set
			{
				if ((this._tmpVehicleNumber != value))
				{
					this.OntmpVehicleNumberChanging(value);
					this.SendPropertyChanging();
					this._tmpVehicleNumber = value;
					this.SendPropertyChanged("tmpVehicleNumber");
					this.OntmpVehicleNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsLicensed", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> YearsLicensed
		{
			get
			{
				return this._YearsLicensed;
			}
			set
			{
				if ((this._YearsLicensed != value))
				{
					this.OnYearsLicensedChanging(value);
					this.SendPropertyChanging();
					this._YearsLicensed = value;
					this.SendPropertyChanged("YearsLicensed");
					this.OnYearsLicensedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsInCollectorCarHobby", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> YearsInCollectorCarHobby
		{
			get
			{
				return this._YearsInCollectorCarHobby;
			}
			set
			{
				if ((this._YearsInCollectorCarHobby != value))
				{
					this.OnYearsInCollectorCarHobbyChanging(value);
					this.SendPropertyChanging();
					this._YearsInCollectorCarHobby = value;
					this.SendPropertyChanged("YearsInCollectorCarHobby");
					this.OnYearsInCollectorCarHobbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptOutMailingsInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> OptOutMailingsInd
		{
			get
			{
				return this._OptOutMailingsInd;
			}
			set
			{
				if ((this._OptOutMailingsInd != value))
				{
					this.OnOptOutMailingsIndChanging(value);
					this.SendPropertyChanging();
					this._OptOutMailingsInd = value;
					this.SendPropertyChanged("OptOutMailingsInd");
					this.OnOptOutMailingsIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstimatedDateOfBirthInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> EstimatedDateOfBirthInd
		{
			get
			{
				return this._EstimatedDateOfBirthInd;
			}
			set
			{
				if ((this._EstimatedDateOfBirthInd != value))
				{
					this.OnEstimatedDateOfBirthIndChanging(value);
					this.SendPropertyChanging();
					this._EstimatedDateOfBirthInd = value;
					this.SendPropertyChanged("EstimatedDateOfBirthInd");
					this.OnEstimatedDateOfBirthIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElectronicRenewalConfirmationDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ElectronicRenewalConfirmationDate
		{
			get
			{
				return this._ElectronicRenewalConfirmationDate;
			}
			set
			{
				if ((this._ElectronicRenewalConfirmationDate != value))
				{
					this.OnElectronicRenewalConfirmationDateChanging(value);
					this.SendPropertyChanging();
					this._ElectronicRenewalConfirmationDate = value;
					this.SendPropertyChanged("ElectronicRenewalConfirmationDate");
					this.OnElectronicRenewalConfirmationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElectronicRenewalSignupDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ElectronicRenewalSignupDate
		{
			get
			{
				return this._ElectronicRenewalSignupDate;
			}
			set
			{
				if ((this._ElectronicRenewalSignupDate != value))
				{
					this.OnElectronicRenewalSignupDateChanging(value);
					this.SendPropertyChanging();
					this._ElectronicRenewalSignupDate = value;
					this.SendPropertyChanged("ElectronicRenewalSignupDate");
					this.OnElectronicRenewalSignupDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportedSeniorCitizenInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> ReportedSeniorCitizenInd
		{
			get
			{
				return this._ReportedSeniorCitizenInd;
			}
			set
			{
				if ((this._ReportedSeniorCitizenInd != value))
				{
					this.OnReportedSeniorCitizenIndChanging(value);
					this.SendPropertyChanging();
					this._ReportedSeniorCitizenInd = value;
					this.SendPropertyChanged("ReportedSeniorCitizenInd");
					this.OnReportedSeniorCitizenIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportedYearsLicensed", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ReportedYearsLicensed
		{
			get
			{
				return this._ReportedYearsLicensed;
			}
			set
			{
				if ((this._ReportedYearsLicensed != value))
				{
					this.OnReportedYearsLicensedChanging(value);
					this.SendPropertyChanging();
					this._ReportedYearsLicensed = value;
					this.SendPropertyChanged("ReportedYearsLicensed");
					this.OnReportedYearsLicensedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryIsAnOrInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> SecondaryIsAnOrInd
		{
			get
			{
				return this._SecondaryIsAnOrInd;
			}
			set
			{
				if ((this._SecondaryIsAnOrInd != value))
				{
					this.OnSecondaryIsAnOrIndChanging(value);
					this.SendPropertyChanging();
					this._SecondaryIsAnOrInd = value;
					this.SendPropertyChanged("SecondaryIsAnOrInd");
					this.OnSecondaryIsAnOrIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeignAddressInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> ForeignAddressInd
		{
			get
			{
				return this._ForeignAddressInd;
			}
			set
			{
				if ((this._ForeignAddressInd != value))
				{
					this.OnForeignAddressIndChanging(value);
					this.SendPropertyChanging();
					this._ForeignAddressInd = value;
					this.SendPropertyChanged("ForeignAddressInd");
					this.OnForeignAddressIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HobbyStartYear", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> HobbyStartYear
		{
			get
			{
				return this._HobbyStartYear;
			}
			set
			{
				if ((this._HobbyStartYear != value))
				{
					this.OnHobbyStartYearChanging(value);
					this.SendPropertyChanging();
					this._HobbyStartYear = value;
					this.SendPropertyChanged("HobbyStartYear");
					this.OnHobbyStartYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearsLicensedReevaluatedForPolicyEffectiveDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> YearsLicensedReevaluatedForPolicyEffectiveDate
		{
			get
			{
				return this._YearsLicensedReevaluatedForPolicyEffectiveDate;
			}
			set
			{
				if ((this._YearsLicensedReevaluatedForPolicyEffectiveDate != value))
				{
					this.OnYearsLicensedReevaluatedForPolicyEffectiveDateChanging(value);
					this.SendPropertyChanging();
					this._YearsLicensedReevaluatedForPolicyEffectiveDate = value;
					this.SendPropertyChanged("YearsLicensedReevaluatedForPolicyEffectiveDate");
					this.OnYearsLicensedReevaluatedForPolicyEffectiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PendingReportedYearsLicensed", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PendingReportedYearsLicensed
		{
			get
			{
				return this._PendingReportedYearsLicensed;
			}
			set
			{
				if ((this._PendingReportedYearsLicensed != value))
				{
					this.OnPendingReportedYearsLicensedChanging(value);
					this.SendPropertyChanging();
					this._PendingReportedYearsLicensed = value;
					this.SendPropertyChanged("PendingReportedYearsLicensed");
					this.OnPendingReportedYearsLicensedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommercialInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> CommercialInd
		{
			get
			{
				return this._CommercialInd;
			}
			set
			{
				if ((this._CommercialInd != value))
				{
					this.OnCommercialIndChanging(value);
					this.SendPropertyChanging();
					this._CommercialInd = value;
					this.SendPropertyChanged("CommercialInd");
					this.OnCommercialIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondaryIsNamedInsuredInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> SecondaryIsNamedInsuredInd
		{
			get
			{
				return this._SecondaryIsNamedInsuredInd;
			}
			set
			{
				if ((this._SecondaryIsNamedInsuredInd != value))
				{
					this.OnSecondaryIsNamedInsuredIndChanging(value);
					this.SendPropertyChanging();
					this._SecondaryIsNamedInsuredInd = value;
					this.SendPropertyChanged("SecondaryIsNamedInsuredInd");
					this.OnSecondaryIsNamedInsuredIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="VarChar(40)", UpdateCheck=UpdateCheck.Never)]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this.OnOccupationChanging(value);
					this.SendPropertyChanging();
					this._Occupation = value;
					this.SendPropertyChanged("Occupation");
					this.OnOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotLicensedInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> NotLicensedInd
		{
			get
			{
				return this._NotLicensedInd;
			}
			set
			{
				if ((this._NotLicensedInd != value))
				{
					this.OnNotLicensedIndChanging(value);
					this.SendPropertyChanging();
					this._NotLicensedInd = value;
					this.SendPropertyChanged("NotLicensedInd");
					this.OnNotLicensedIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ActiveDate
		{
			get
			{
				return this._ActiveDate;
			}
			set
			{
				if ((this._ActiveDate != value))
				{
					this.OnActiveDateChanging(value);
					this.SendPropertyChanging();
					this._ActiveDate = value;
					this.SendPropertyChanged("ActiveDate");
					this.OnActiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlexTierTriggerDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> FlexTierTriggerDate
		{
			get
			{
				return this._FlexTierTriggerDate;
			}
			set
			{
				if ((this._FlexTierTriggerDate != value))
				{
					this.OnFlexTierTriggerDateChanging(value);
					this.SendPropertyChanging();
					this._FlexTierTriggerDate = value;
					this.SendPropertyChanged("FlexTierTriggerDate");
					this.OnFlexTierTriggerDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerAccountSTPUWRptResponseDriverFK", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CustomerAccountSTPUWRptResponseDriverFK
		{
			get
			{
				return this._CustomerAccountSTPUWRptResponseDriverFK;
			}
			set
			{
				if ((this._CustomerAccountSTPUWRptResponseDriverFK != value))
				{
					this.OnCustomerAccountSTPUWRptResponseDriverFKChanging(value);
					this.SendPropertyChanging();
					this._CustomerAccountSTPUWRptResponseDriverFK = value;
					this.SendPropertyChanged("CustomerAccountSTPUWRptResponseDriverFK");
					this.OnCustomerAccountSTPUWRptResponseDriverFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthFirstLicensed", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MonthFirstLicensed
		{
			get
			{
				return this._MonthFirstLicensed;
			}
			set
			{
				if ((this._MonthFirstLicensed != value))
				{
					this.OnMonthFirstLicensedChanging(value);
					this.SendPropertyChanging();
					this._MonthFirstLicensed = value;
					this.SendPropertyChanged("MonthFirstLicensed");
					this.OnMonthFirstLicensedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearFirstLicensed", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> YearFirstLicensed
		{
			get
			{
				return this._YearFirstLicensed;
			}
			set
			{
				if ((this._YearFirstLicensed != value))
				{
					this.OnYearFirstLicensedChanging(value);
					this.SendPropertyChanging();
					this._YearFirstLicensed = value;
					this.SendPropertyChanged("YearFirstLicensed");
					this.OnYearFirstLicensedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonFK", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PersonFK
		{
			get
			{
				return this._PersonFK;
			}
			set
			{
				if ((this._PersonFK != value))
				{
					this.OnPersonFKChanging(value);
					this.SendPropertyChanging();
					this._PersonFK = value;
					this.SendPropertyChanged("PersonFK");
					this.OnPersonFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DriversLicenseNoEncrypted", DbType="VarBinary(256)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DriversLicenseNoEncrypted
		{
			get
			{
				return this._DriversLicenseNoEncrypted;
			}
			set
			{
				if ((this._DriversLicenseNoEncrypted != value))
				{
					this.OnDriversLicenseNoEncryptedChanging(value);
					this.SendPropertyChanging();
					this._DriversLicenseNoEncrypted = value;
					this.SendPropertyChanged("DriversLicenseNoEncrypted");
					this.OnDriversLicenseNoEncryptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIFMFlexGrandfatherInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> DIFMFlexGrandfatherInd
		{
			get
			{
				return this._DIFMFlexGrandfatherInd;
			}
			set
			{
				if ((this._DIFMFlexGrandfatherInd != value))
				{
					this.OnDIFMFlexGrandfatherIndChanging(value);
					this.SendPropertyChanging();
					this._DIFMFlexGrandfatherInd = value;
					this.SendPropertyChanged("DIFMFlexGrandfatherInd");
					this.OnDIFMFlexGrandfatherIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LicensedLessThanThreeYearsInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> LicensedLessThanThreeYearsInd
		{
			get
			{
				return this._LicensedLessThanThreeYearsInd;
			}
			set
			{
				if ((this._LicensedLessThanThreeYearsInd != value))
				{
					this.OnLicensedLessThanThreeYearsIndChanging(value);
					this.SendPropertyChanging();
					this._LicensedLessThanThreeYearsInd = value;
					this.SendPropertyChanged("LicensedLessThanThreeYearsInd");
					this.OnLicensedLessThanThreeYearsIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnknownDLNoInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> UnknownDLNoInd
		{
			get
			{
				return this._UnknownDLNoInd;
			}
			set
			{
				if ((this._UnknownDLNoInd != value))
				{
					this.OnUnknownDLNoIndChanging(value);
					this.SendPropertyChanging();
					this._UnknownDLNoInd = value;
					this.SendPropertyChanged("UnknownDLNoInd");
					this.OnUnknownDLNoIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelevantDate", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> RelevantDate
		{
			get
			{
				return this._RelevantDate;
			}
			set
			{
				if ((this._RelevantDate != value))
				{
					this.OnRelevantDateChanging(value);
					this.SendPropertyChanging();
					this._RelevantDate = value;
					this.SendPropertyChanged("RelevantDate");
					this.OnRelevantDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKABGridStepScoreFK", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> LKABGridStepScoreFK
		{
			get
			{
				return this._LKABGridStepScoreFK;
			}
			set
			{
				if ((this._LKABGridStepScoreFK != value))
				{
					this.OnLKABGridStepScoreFKChanging(value);
					this.SendPropertyChanging();
					this._LKABGridStepScoreFK = value;
					this.SendPropertyChanged("LKABGridStepScoreFK");
					this.OnLKABGridStepScoreFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Customer", Storage="_Customers", ThisKey="CustomerPK", OtherKey="PreferredContactFK")]
		public EntitySet<Customer> Customers
		{
			get
			{
				return this._Customers;
			}
			set
			{
				this._Customers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_CustomerPhone", Storage="_CustomerPhones", ThisKey="CustomerPK", OtherKey="CustomerFK")]
		public EntitySet<CustomerPhone> CustomerPhones
		{
			get
			{
				return this._CustomerPhones;
			}
			set
			{
				this._CustomerPhones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_CustomerEmail", Storage="_CustomerEmails", ThisKey="CustomerPK", OtherKey="CustomerFK")]
		public EntitySet<CustomerEmail> CustomerEmails
		{
			get
			{
				return this._CustomerEmails;
			}
			set
			{
				this._CustomerEmails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_Customer", Storage="_Customer1", ThisKey="PreferredContactFK", OtherKey="CustomerPK", IsForeignKey=true)]
		public Customer Customer1
		{
			get
			{
				return this._Customer1.Entity;
			}
			set
			{
				Customer previousValue = this._Customer1.Entity;
				if (((previousValue != value) 
							|| (this._Customer1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer1.Entity = null;
						previousValue.Customers.Remove(this);
					}
					this._Customer1.Entity = value;
					if ((value != null))
					{
						value.Customers.Add(this);
						this._PreferredContactFK = value.CustomerPK;
					}
					else
					{
						this._PreferredContactFK = default(Nullable<int>);
					}
					this.SendPropertyChanged("Customer1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Customers(Customer entity)
		{
			this.SendPropertyChanging();
			entity.Customer1 = this;
		}
		
		private void detach_Customers(Customer entity)
		{
			this.SendPropertyChanging();
			entity.Customer1 = null;
		}
		
		private void attach_CustomerPhones(CustomerPhone entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_CustomerPhones(CustomerPhone entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
		
		private void attach_CustomerEmails(CustomerEmail entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_CustomerEmails(CustomerEmail entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerPhone")]
	public partial class CustomerPhone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerPhonePK;
		
		private System.Nullable<int> _LKPhoneFK;
		
		private System.Nullable<int> _CustomerFK;
		
		private string _AreaCode;
		
		private string _Prefix;
		
		private string _Suffix;
		
		private string _Extension;
		
		private System.Nullable<System.DateTime> _EffectiveDate;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private System.DateTime _LastUpdTimestamp;
		
		private string _LastUpdUser;
		
		private bool _DefaultPhoneInd;
		
		private System.Data.Linq.Binary _HIARowVersion;
		
		private System.Nullable<int> _AptifyCustomerPhoneID;
		
		private EntityRef<Customer> _Customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerPhonePKChanging(int value);
    partial void OnCustomerPhonePKChanged();
    partial void OnLKPhoneFKChanging(System.Nullable<int> value);
    partial void OnLKPhoneFKChanged();
    partial void OnCustomerFKChanging(System.Nullable<int> value);
    partial void OnCustomerFKChanged();
    partial void OnAreaCodeChanging(string value);
    partial void OnAreaCodeChanged();
    partial void OnPrefixChanging(string value);
    partial void OnPrefixChanged();
    partial void OnSuffixChanging(string value);
    partial void OnSuffixChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnEffectiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEffectiveDateChanged();
    partial void OnExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpirationDateChanged();
    partial void OnLastUpdTimestampChanging(System.DateTime value);
    partial void OnLastUpdTimestampChanged();
    partial void OnLastUpdUserChanging(string value);
    partial void OnLastUpdUserChanged();
    partial void OnDefaultPhoneIndChanging(bool value);
    partial void OnDefaultPhoneIndChanged();
    partial void OnHIARowVersionChanging(System.Data.Linq.Binary value);
    partial void OnHIARowVersionChanged();
    partial void OnAptifyCustomerPhoneIDChanging(System.Nullable<int> value);
    partial void OnAptifyCustomerPhoneIDChanged();
    #endregion
		
		public CustomerPhone()
		{
			this._Customer = default(EntityRef<Customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerPhonePK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CustomerPhonePK
		{
			get
			{
				return this._CustomerPhonePK;
			}
			set
			{
				if ((this._CustomerPhonePK != value))
				{
					this.OnCustomerPhonePKChanging(value);
					this.SendPropertyChanging();
					this._CustomerPhonePK = value;
					this.SendPropertyChanged("CustomerPhonePK");
					this.OnCustomerPhonePKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKPhoneFK", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> LKPhoneFK
		{
			get
			{
				return this._LKPhoneFK;
			}
			set
			{
				if ((this._LKPhoneFK != value))
				{
					this.OnLKPhoneFKChanging(value);
					this.SendPropertyChanging();
					this._LKPhoneFK = value;
					this.SendPropertyChanged("LKPhoneFK");
					this.OnLKPhoneFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerFK", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CustomerFK
		{
			get
			{
				return this._CustomerFK;
			}
			set
			{
				if ((this._CustomerFK != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerFKChanging(value);
					this.SendPropertyChanging();
					this._CustomerFK = value;
					this.SendPropertyChanged("CustomerFK");
					this.OnCustomerFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaCode", DbType="Char(3)", UpdateCheck=UpdateCheck.Never)]
		public string AreaCode
		{
			get
			{
				return this._AreaCode;
			}
			set
			{
				if ((this._AreaCode != value))
				{
					this.OnAreaCodeChanging(value);
					this.SendPropertyChanging();
					this._AreaCode = value;
					this.SendPropertyChanged("AreaCode");
					this.OnAreaCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prefix", DbType="Char(3)", UpdateCheck=UpdateCheck.Never)]
		public string Prefix
		{
			get
			{
				return this._Prefix;
			}
			set
			{
				if ((this._Prefix != value))
				{
					this.OnPrefixChanging(value);
					this.SendPropertyChanging();
					this._Prefix = value;
					this.SendPropertyChanged("Prefix");
					this.OnPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suffix", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string Suffix
		{
			get
			{
				return this._Suffix;
			}
			set
			{
				if ((this._Suffix != value))
				{
					this.OnSuffixChanging(value);
					this.SendPropertyChanging();
					this._Suffix = value;
					this.SendPropertyChanged("Suffix");
					this.OnSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="Char(5)", UpdateCheck=UpdateCheck.Never)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectiveDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> EffectiveDate
		{
			get
			{
				return this._EffectiveDate;
			}
			set
			{
				if ((this._EffectiveDate != value))
				{
					this.OnEffectiveDateChanging(value);
					this.SendPropertyChanging();
					this._EffectiveDate = value;
					this.SendPropertyChanged("EffectiveDate");
					this.OnEffectiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdTimestamp", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastUpdTimestamp
		{
			get
			{
				return this._LastUpdTimestamp;
			}
			set
			{
				if ((this._LastUpdTimestamp != value))
				{
					this.OnLastUpdTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdTimestamp = value;
					this.SendPropertyChanged("LastUpdTimestamp");
					this.OnLastUpdTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdUser", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string LastUpdUser
		{
			get
			{
				return this._LastUpdUser;
			}
			set
			{
				if ((this._LastUpdUser != value))
				{
					this.OnLastUpdUserChanging(value);
					this.SendPropertyChanging();
					this._LastUpdUser = value;
					this.SendPropertyChanged("LastUpdUser");
					this.OnLastUpdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultPhoneInd", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool DefaultPhoneInd
		{
			get
			{
				return this._DefaultPhoneInd;
			}
			set
			{
				if ((this._DefaultPhoneInd != value))
				{
					this.OnDefaultPhoneIndChanging(value);
					this.SendPropertyChanging();
					this._DefaultPhoneInd = value;
					this.SendPropertyChanged("DefaultPhoneInd");
					this.OnDefaultPhoneIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIARowVersion", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HIARowVersion
		{
			get
			{
				return this._HIARowVersion;
			}
			set
			{
				if ((this._HIARowVersion != value))
				{
					this.OnHIARowVersionChanging(value);
					this.SendPropertyChanging();
					this._HIARowVersion = value;
					this.SendPropertyChanged("HIARowVersion");
					this.OnHIARowVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AptifyCustomerPhoneID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> AptifyCustomerPhoneID
		{
			get
			{
				return this._AptifyCustomerPhoneID;
			}
			set
			{
				if ((this._AptifyCustomerPhoneID != value))
				{
					this.OnAptifyCustomerPhoneIDChanging(value);
					this.SendPropertyChanging();
					this._AptifyCustomerPhoneID = value;
					this.SendPropertyChanged("AptifyCustomerPhoneID");
					this.OnAptifyCustomerPhoneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_CustomerPhone", Storage="_Customer", ThisKey="CustomerFK", OtherKey="CustomerPK", IsForeignKey=true)]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.CustomerPhones.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.CustomerPhones.Add(this);
						this._CustomerFK = value.CustomerPK;
					}
					else
					{
						this._CustomerFK = default(Nullable<int>);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerEmail")]
	public partial class CustomerEmail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerEmailPK;
		
		private int _CustomerFK;
		
		private string _EmailAddress;
		
		private int _LKEmailTypeFK;
		
		private System.DateTime _EffectiveDate;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private System.DateTime _LastUpdTimestamp;
		
		private string _LastUpdUser;
		
		private bool _DefaultEmailInd;
		
		private System.Nullable<bool> _LoginIDInd;
		
		private System.Data.Linq.Binary _HIARowVersion;
		
		private System.Nullable<bool> _PaperlessInd;
		
		private System.Nullable<int> _LKLoginTrackingFK;
		
		private System.Nullable<bool> _UndeliverableInd;
		
		private EntityRef<Customer> _Customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerEmailPKChanging(int value);
    partial void OnCustomerEmailPKChanged();
    partial void OnCustomerFKChanging(int value);
    partial void OnCustomerFKChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnLKEmailTypeFKChanging(int value);
    partial void OnLKEmailTypeFKChanged();
    partial void OnEffectiveDateChanging(System.DateTime value);
    partial void OnEffectiveDateChanged();
    partial void OnExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpirationDateChanged();
    partial void OnLastUpdTimestampChanging(System.DateTime value);
    partial void OnLastUpdTimestampChanged();
    partial void OnLastUpdUserChanging(string value);
    partial void OnLastUpdUserChanged();
    partial void OnDefaultEmailIndChanging(bool value);
    partial void OnDefaultEmailIndChanged();
    partial void OnLoginIDIndChanging(System.Nullable<bool> value);
    partial void OnLoginIDIndChanged();
    partial void OnHIARowVersionChanging(System.Data.Linq.Binary value);
    partial void OnHIARowVersionChanged();
    partial void OnPaperlessIndChanging(System.Nullable<bool> value);
    partial void OnPaperlessIndChanged();
    partial void OnLKLoginTrackingFKChanging(System.Nullable<int> value);
    partial void OnLKLoginTrackingFKChanged();
    partial void OnUndeliverableIndChanging(System.Nullable<bool> value);
    partial void OnUndeliverableIndChanged();
    #endregion
		
		public CustomerEmail()
		{
			this._Customer = default(EntityRef<Customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerEmailPK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CustomerEmailPK
		{
			get
			{
				return this._CustomerEmailPK;
			}
			set
			{
				if ((this._CustomerEmailPK != value))
				{
					this.OnCustomerEmailPKChanging(value);
					this.SendPropertyChanging();
					this._CustomerEmailPK = value;
					this.SendPropertyChanged("CustomerEmailPK");
					this.OnCustomerEmailPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerFK", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CustomerFK
		{
			get
			{
				return this._CustomerFK;
			}
			set
			{
				if ((this._CustomerFK != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerFKChanging(value);
					this.SendPropertyChanging();
					this._CustomerFK = value;
					this.SendPropertyChanged("CustomerFK");
					this.OnCustomerFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKEmailTypeFK", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int LKEmailTypeFK
		{
			get
			{
				return this._LKEmailTypeFK;
			}
			set
			{
				if ((this._LKEmailTypeFK != value))
				{
					this.OnLKEmailTypeFKChanging(value);
					this.SendPropertyChanging();
					this._LKEmailTypeFK = value;
					this.SendPropertyChanged("LKEmailTypeFK");
					this.OnLKEmailTypeFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectiveDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime EffectiveDate
		{
			get
			{
				return this._EffectiveDate;
			}
			set
			{
				if ((this._EffectiveDate != value))
				{
					this.OnEffectiveDateChanging(value);
					this.SendPropertyChanging();
					this._EffectiveDate = value;
					this.SendPropertyChanged("EffectiveDate");
					this.OnEffectiveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdTimestamp", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastUpdTimestamp
		{
			get
			{
				return this._LastUpdTimestamp;
			}
			set
			{
				if ((this._LastUpdTimestamp != value))
				{
					this.OnLastUpdTimestampChanging(value);
					this.SendPropertyChanging();
					this._LastUpdTimestamp = value;
					this.SendPropertyChanged("LastUpdTimestamp");
					this.OnLastUpdTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdUser", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string LastUpdUser
		{
			get
			{
				return this._LastUpdUser;
			}
			set
			{
				if ((this._LastUpdUser != value))
				{
					this.OnLastUpdUserChanging(value);
					this.SendPropertyChanging();
					this._LastUpdUser = value;
					this.SendPropertyChanged("LastUpdUser");
					this.OnLastUpdUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultEmailInd", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool DefaultEmailInd
		{
			get
			{
				return this._DefaultEmailInd;
			}
			set
			{
				if ((this._DefaultEmailInd != value))
				{
					this.OnDefaultEmailIndChanging(value);
					this.SendPropertyChanging();
					this._DefaultEmailInd = value;
					this.SendPropertyChanged("DefaultEmailInd");
					this.OnDefaultEmailIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginIDInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> LoginIDInd
		{
			get
			{
				return this._LoginIDInd;
			}
			set
			{
				if ((this._LoginIDInd != value))
				{
					this.OnLoginIDIndChanging(value);
					this.SendPropertyChanging();
					this._LoginIDInd = value;
					this.SendPropertyChanged("LoginIDInd");
					this.OnLoginIDIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIARowVersion", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HIARowVersion
		{
			get
			{
				return this._HIARowVersion;
			}
			set
			{
				if ((this._HIARowVersion != value))
				{
					this.OnHIARowVersionChanging(value);
					this.SendPropertyChanging();
					this._HIARowVersion = value;
					this.SendPropertyChanged("HIARowVersion");
					this.OnHIARowVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaperlessInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> PaperlessInd
		{
			get
			{
				return this._PaperlessInd;
			}
			set
			{
				if ((this._PaperlessInd != value))
				{
					this.OnPaperlessIndChanging(value);
					this.SendPropertyChanging();
					this._PaperlessInd = value;
					this.SendPropertyChanged("PaperlessInd");
					this.OnPaperlessIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LKLoginTrackingFK", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> LKLoginTrackingFK
		{
			get
			{
				return this._LKLoginTrackingFK;
			}
			set
			{
				if ((this._LKLoginTrackingFK != value))
				{
					this.OnLKLoginTrackingFKChanging(value);
					this.SendPropertyChanging();
					this._LKLoginTrackingFK = value;
					this.SendPropertyChanged("LKLoginTrackingFK");
					this.OnLKLoginTrackingFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UndeliverableInd", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> UndeliverableInd
		{
			get
			{
				return this._UndeliverableInd;
			}
			set
			{
				if ((this._UndeliverableInd != value))
				{
					this.OnUndeliverableIndChanging(value);
					this.SendPropertyChanging();
					this._UndeliverableInd = value;
					this.SendPropertyChanged("UndeliverableInd");
					this.OnUndeliverableIndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customer_CustomerEmail", Storage="_Customer", ThisKey="CustomerFK", OtherKey="CustomerPK", IsForeignKey=true)]
		public Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.CustomerEmails.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.CustomerEmails.Add(this);
						this._CustomerFK = value.CustomerPK;
					}
					else
					{
						this._CustomerFK = default(int);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
